
name: tasks
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  circular_check_box: ^1.0.4
  intl: ^0.16.1
  sqflite: ^2.0.0+2
  path_provider: ^2.0.1
  flutter_local_notifications: ^4.0.1+2
  timezone: ^0.6.1
  flutter_native_timezone: ^1.0.10
  page_transition: "^1.1.7+6"
  smart_flare: any
  flare_flutter: ^2.0.6
  
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/order_by.flr

  fonts: 
    - family: "Circular Std"
      fonts:
        - asset: "assets/fonts/CircularStd-Book.ttf"
          weight: 400
        - asset: "assets/fonts/CircularStd-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/CircularStd-Bold.ttf"
          weight: 600
        - asset: "assets/fonts/CircularStd-Black.ttf"
          weight: 700