
name: tasks
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  circular_check_box: ^1.0.4
  intl: ^0.16.1
  
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts: 
    - family: "Circular Std"
      fonts:
        - asset: "assets/fonts/CircularStd-Book.ttf"
          weight: 400
        - asset: "assets/fonts/CircularStd-Medium.ttf"
          weight: 500
        - asset: "assets/fonts/CircularStd-Bold.ttf"
          weight: 600
        - asset: "assets/fonts/CircularStd-Black.ttf"
          weight: 700