/// Flutter icons TaskIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TaskIcons
///      fonts:
///       - asset: fonts/TaskIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TaskIcons {
  TaskIcons._();

  static const _kFontFam = 'TaskIcons';
  static const String _kFontPkg = null;

  static const IconData date = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation_mark = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equalizer = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData approve = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
